### ISSUE TITLE
Header-only API for DataFrameSubsetVisitors

### ISSUE THREAD

**Issue by lionel-** [hadley/dplyr#1814]
Would you consider keeping the `DataFrameSubsetVisitors` class as header-only? This would make it easier to reuse in external packages.

Purrr has stopped loading a while ago (issue hadley/purrr#196) because dplyr is moving definitions inside unshipped cpp files, cf https://github.com/hadley/dplyr/commit/04704bff3fd2969607fd648e362b289483041a3d.

**Comment by yutannihilation** [comment]
I saw this error message when trying to install purrr:

```r
rows.o:rows.cpp:(.text+0x991): undefined reference to `dplyr::DataFrameSubsetVisitors::DataFrameSubsetVisitors(Rcpp::DataFrame_Impl<Rcpp::PreserveStorage> const&)'
```

I'm not familiar with C++, but it seems that this issue is caused by something about template class (`Rcpp::DataFrame` is a template class, right?).

c++ - "Undefined reference to" template class constructor - Stack Overflow
http://stackoverflow.com/questions/8752837/undefined-reference-to-template-class-constructor/8752879#8752879

> The code in a template is merely a 'pattern' known to the compiler. The compiler won't compile the constructors `cola<float>::cola(...)` and `cola<string>::cola(...)` until it is forced to do so. And we must ensure that this compilation happens for the constructors at least once in the entire compilation process, or we will get the 'undefined reference' error.
>   
> ...snip...
>  
> The problem is caused by the fact that `main.cpp` and `cola.cpp` will be compiled separately first. In main.cpp, the compiler will implicitly instantiate the template classes `cola<float>` and `cola<string>` because those particular instantiations are used in `main.cpp`. The bad news is that the implementations of those member functions are not in `main.cpp`, nor in any header file included in `main.cpp`, and therefore the compiler can't include complete versions of those functions in `main.o`.

This SO answer suggests two possible solutions:

1. Explicitly instantiate the template, and its member definitions
2. Copy the code into the relevant header file

In my understanding, 1 means to discard the power of abstraction by Rcpp, and 2 means just to revert https://github.com/hadley/dplyr/commit/04704bff3fd2969607fd648e362b289483041a3d.

**Comment by lionel-** [comment]
The issue is that the DataFrameSubsetVisitors stopped being a headers-only class when some of its definitions got moved into a .cpp file in the src/ folder. That's a problem because when dplyr gets installed, only the .h files in the inst/ folder are copied along. The end result is that when we compile purrr the linker will mark the functions with missing definitions as externally provided symbols.

One way out would be to link purrr against the dplyr shared object so that it can resolve those external symbols, but I'm not sure how to do it properly or even if there is a proper way to do this with R packages.

The other way out is to keep this class as headers-only. But Romain may have good reason not to do so. Another issue is that this class can only compile when we set the `-DCOMPILING_DPLYR` flag, and apparently that flag is only meant for dplyr, not 3rd party packages. Bottom line, I don't think @romainfrancois has ever considered that class to be part of a public API, though he did unformally mention it on Stack Overflow if I remember correctly.

**Comment by yutannihilation** [comment]
@lionel- 
Ah, sorry for closing this issue without notifying you... Please reopen this if more discussion is needed about the `-DCOMPILING_DPLYR` flag and so on.

**Comment by lionel-** [comment]
that's good thanks. We are moving all the data frame mapping stuff to dplyr so in the future we won't need to compile or link purrr against dplyr.

**Comment by yutannihilation** [comment]
Wow, sounds great. I'm looking forward the future :)
